FROM node:alpine AS development

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm 
RUN npm install -g bun 

COPY . .

RUN pnpm install

RUN pnpm run build

FROM node:alpine AS production

WORKDIR /usr/src/app

COPY --from=development /usr/src/app/dist ./dist